import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>LIMEFIT backend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <main className='container'>
        <h1>LIMEFIT backend</h1>
        <section>
          <form>
            <div className='grid'>
              <input type="text" placeholder="DNI" />
              <input type="password" placeholder="Contraseña" />
              <button>Ingresar</button>
            </div>
          </form>
        </section>
        <p>
          Este es el backend de la aplicación LIMEFIT
        </p>
        </main>

      </main>
    </>
  )
}
